INSERT INTO cocktail_db.ingredient VALUES (1,'Light rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (2,'Light rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (3,'Applejack','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (4,'Ginger beer','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (5,'Grapefruit juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (6,'Aejo rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (7,'Lemon peel','','Garnish',0);
 INSERT INTO cocktail_db.ingredient VALUES (8,'Orange juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (9,'Lemon juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (10,'Ginger ale','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (11,'Gin','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (12,'Orange bitters','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (13,'Orange','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (14,'Cherry','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (15,'Triple sec','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (16,'Lime juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (17,'Sugar','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (18,'Egg white','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (19,'Mint','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (20,'Dark rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (21,'Peach nectar','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (22,'Grenadine','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (23,'Strawberry schnapps','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (24,'Sweet Vermouth','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (25,'Cranberry juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (26,'Sherry','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (27,'Club soda','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (28,'Scotch','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (29,'Dry Vermouth','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (30,'Apricot brandy','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (31,'Lime','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (32,'Southern Comfort','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (33,'Amaretto','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (34,'Sloe gin','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (35,'Yellow Chartreuse','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (36,'Creme de Cacao','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (37,'Light cream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (38,'Nutmeg','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (39,'Brandy','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (40,'Lemon vodka','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (41,'Pineapple juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (42,'Blended whiskey','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (43,'Bourbon','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (44,'Blackberry brandy','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (45,'Kummel','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (46,'Kahlua','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (47,'White Creme de Menthe','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (48,'Tea','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (49,'Whipped cream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (50,'Apple brandy','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (51,'Champagne','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (52,'Green Creme de Menthe','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (53,'Grand Marnier','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (54,'Wine','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (55,'Benedictine','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (56,'Bitters','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (57,'Banana','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (58,'Coffee liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (59,'Vodka','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (60,'Carbonated water','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (61,'Tequila','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (62,'Tomato juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (63,'Tabasco sauce','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (64,'Celery salt','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (65,'Lemon','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (66,'Worcestershire sauce','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (67,'Blue Curacao','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (68,'Lemonade','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (69,'Salt','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (70,'Tia maria','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (71,'Maraschino cherry','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (72,'Maraschino liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (73,'Powdered sugar','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (74,'Water','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (75,'Egg','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (76,'Cachaca','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (77,'Cognac','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (78,'Egg yolk','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (79,'Cherry brandy','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (80,'Chocolate icecream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (81,'Port','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (82,'CocaCola','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (83,'Dubonnet Rouge','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (84,'Sugar syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (85,'Ice','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (86,'Pineapple','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (87,'Orange spiral','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (88,'Tonic water','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (89,'Orange peel','','Garnish',0);
 INSERT INTO cocktail_db.ingredient VALUES (90,'Strawberries','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (91,'Heavy cream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (92,'Galliano','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (93,'Olive','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (94,'Irish whiskey','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (95,'Peach brandy','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (96,'Sweet and sour','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (97,'Green Chartreuse','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (98,'Drambuie','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (99,'Orgeat syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (100,'Red wine','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (101,'Raspberry syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (102,'Coffee brandy','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (103,'Lime vodka','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (104,'Lemonlime soda','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (105,'Rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (106,'Milk','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (107,'151 proof rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (108,'Lime peel','','Garnish',0);
 INSERT INTO cocktail_db.ingredient VALUES (109,'Ricard','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (110,'Peychaud bitters','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (111,'Curacao','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (112,'Anisette','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (113,'Cointreau','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (114,'Anis','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (115,'Maple syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (116,'Creme de Cassis','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (117,'Grape juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (118,'Cream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (119,'Apple juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (120,'Passion fruit juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (121,'Carrot','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (122,'Soda water','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (123,'Yoghurt','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (124,'Honey','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (125,'Chocolate syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (126,'Apple','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (127,'Fruit juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (128,'Fruit','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (129,'Mint syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (130,'Cumin seed','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (131,'Asafoetida','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (132,'Mango','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (133,'Ginger','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (134,'Cayenne pepper','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (135,'Aperol','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (136,'Cantaloupe','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (137,'Berries','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (138,'Grapes','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (139,'Kiwi','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (140,'Papaya','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (141,'Cocoa powder','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (142,'Cornstarch','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (143,'Chocolate','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (144,'Cinnamon','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (145,'Vanilla','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (146,'Butter','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (147,'Vanilla extract','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (148,'Halfandhalf','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (149,'Marshmallows','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (150,'Espresso','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (151,'Absolut Citron','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (152,'Peach schnapps','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (153,'Peach Vodka','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (154,'Sirup of roses','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (155,'Ouzo','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (156,'Baileys irish cream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (157,'Jgermeister','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (158,'Coffee','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (159,'Grain alcohol','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (160,'Spiced rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (161,'Cardamom','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (162,'Cloves','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (163,'Black pepper','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (164,'Coriander','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (165,'Whipping cream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (166,'Condensed milk','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (167,'Anise','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (168,'Licorice root','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (169,'Wormwood','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (170,'Apricot','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (171,'Almond flavoring','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (172,'Food coloring','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (173,'Glycerine','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (174,'Angelica root','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (175,'Almond','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (176,'Allspice','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (177,'Marjoram leaves','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (178,'Caramel coloring','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (179,'Cranberries','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (180,'Peppermint extract','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (181,'Coconut syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (182,'Johnnie Walker','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (183,'Fennel seeds','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (184,'Brown sugar','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (185,'Guava juice','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (186,'Apple cider','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (187,'Rye whiskey','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (188,'Everclear','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (189,'KoolAid','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (190,'Carbonated soft drink','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (191,'Sherbet','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (192,'Fresca','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (193,'Firewater','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (194,'Absolut Peppar','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (195,'Cherry liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (196,'Frangelico','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (197,'Lager','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (198,'Cider','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (199,'Blackcurrant cordial','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (200,'Sour mix','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (201,'Whiskey','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (202,'Midori melon liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (203,'Angostura bitters','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (204,'Hot Damn','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (205,'Beer','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (206,'Dr Pepper','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (207,'Pisco','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (208,'White rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (209,'Irish cream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (210,'Goldschlager','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (211,'Chocolate liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (212,'Ale','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (213,'Guinness stout','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (214,'Sambuca','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (215,'Passion fruit syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (216,'Vanilla icecream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (217,'Oreo cookie','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (218,'Erin Cream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (219,'Advocaat','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (220,'Sprite','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (221,'Pink lemonade','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (222,'Iced tea','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (223,'Sarsaparilla','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (224,'7Up','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (225,'Apple schnapps','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (226,'Peppermint schnapps','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (227,'Jack Daniels','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (228,'Jim Beam','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (229,'Absolut Vodka','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (230,'Pina colada mix','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (231,'Daiquiri mix','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (232,'Butterscotch schnapps','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (233,'Coconut liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (234,'Crown Royal','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (235,'Vermouth','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (236,'Chambord raspberry liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (237,'Godiva liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (238,'Absolut Kurant','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (239,'Pisang Ambon','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (240,'Bitter lemon','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (241,'Cherry Heering','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (242,'Hot chocolate','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (243,'Creme de Banane','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (244,'Malibu rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (245,'Dark Creme de Cacao','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (246,'Vanilla vodka','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (247,'Grape soda','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (248,'Wild Turkey','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (249,'Candy','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (250,'Banana liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (251,'Kiwi liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (252,'Peachtree schnapps','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (253,'Surge','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (254,'Jello','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (255,'Cranberry vodka','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (256,'Apfelkorn','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (257,'Schweppes Russchian','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (258,'Fruit punch','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (259,'Corona','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (260,'Bacardi Limon','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (261,'Yukon Jack','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (262,'Tropicana','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (263,'Root beer','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (264,'Cherries','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (265,'Coconut rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (266,'Aquavit','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (267,'Campari','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (268,'Chocolate milk','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (269,'Kirschwasser','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (270,'Strawberry liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (271,'Black Sambuca','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (272,'Blackcurrant squash','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (273,'Zima','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (274,'Pepsi Cola','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (275,'Orange Curacao','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (276,'Cream of coconut','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (277,'Absinthe','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (278,'Whisky','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (279,'Tennessee whiskey','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (280,'Limeade','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (281,'Melon liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (282,'Mountain Dew','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (283,'Rumple Minze','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (284,'Corn syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (285,'Gold tequila','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (286,'Lime juice cordial','','Juice',0);
 INSERT INTO cocktail_db.ingredient VALUES (287,'Blueberry schnapps','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (288,'Maui','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (289,'Agave Syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (290,'Raspberry vodka','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (291,'Cherry Grenadine','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (292,'demerara Sugar','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (293,'Baileys irish cream','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (294,'Olive Brine','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (295,'Pineapple Syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (296,'St Germain','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (297,'Pepper','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (298,'Lavender','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (299,'Peach Bitters','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (300,'Coconut milk','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (301,'Prosecco','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (302,'Creme de Mure','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (303,'Raspberry Liqueur','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (304,'Lillet Blanc','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (305,'caramel sauce','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (306,'chocolate sauce','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (307,'Minisnickers bars','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (308,'Fresh Lemon Juice','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (309,'Fresh Lime Juice','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (310,'Salted Chocolate','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (311,'Gold rum','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (312,'Blackberries','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (313,'Pernod','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (314,'Rosemary','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (315,'Lillet','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (316,'Bailey','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (317,'Jagermeister','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (318,'Passoa','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (319,'Elderflower cordial','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (320,'Rosso Vermouth','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (321,'Blended Scotch','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (322,'Honey syrup','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (323,'Ginger Syrup','','Hard liquor',1);
 INSERT INTO cocktail_db.ingredient VALUES (324,'Islay single malt Scotch','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (325,'Falernum','','',0);
 INSERT INTO cocktail_db.ingredient VALUES (326,'blackstrap rum','','Hard liquor',1);
;
